import { Roboto } from "next/font/google";
import "./[locale]/globals.css";
import Header from "./[locale]/_components/Header";
import Footer from "./[locale]/_components/Footer";
import WhatsAppIcon from "./[locale]/_components/WhatsAppIcon";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Top-Notch Patient Experience in Turkiye",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <WhatsAppIcon/>
        <Footer />
      </body>
    </html>
  );
}
